Added customizability
lohanidamodar/clean_nepali_calendar pull request #7
Opened 2020-11-26 02:50 UTC by stha-ums

I hope these features would be beneficial.

Added Features:

1. Height parameter for calendar cell height and header height,
2. Builder function for empty cell builder, (empty means the cell that does not contain date )
3. exposed call back function on month change.  

simple possibility,

![0-02-03-f6f3344a84e17758a74244a762458bd63c313fb7fcb36a714b7499f6fddfb91a_206685174312da](https://user-images.githubusercontent.com/34161121/100302280-1bb5eb00-2fc2-11eb-8d77-55d7531e49b2.jpg)

2020-11-26 03:42 UTC, lohanidamodar commented
@stha-ums Wow, great going! Also, next time work on develop and Open PRs on develop branch.

2020-11-26 04:20 UTC, stha-ums commented
Sure

2020-12-04 08:27 UTC, lohanidamodar approved these changes

2020-12-05 08:25 UTC, lohanidamodar requested changes
बिहिबार हुनु पर्ने बिहिवार भएछ same for शनिबार

2020-12-05 12:25 UTC, stha-ums commented
वार hunxa, not बार

2020-12-05 13:28 UTC, lohanidamodar commented
@stha-ums I think बार नै हुन्छ not वार , confirm with dictionary too..

2020-12-10 10:37 UTC, lohanidamodar commented on lib/src/days_view.dart
> +  "मंगलवार",
should be मंगलबार

2020-12-10 10:37 UTC, lohanidamodar commented on lib/src/days_view.dart
> +  "बिहिवार",
बिहिबार

2020-12-10 10:40 UTC, lohanidamodar commented on lib/src/days_view.dart
> +  "शनिवार"
शनिबार

2021-05-02 06:24 UTC, closed without merging